Add --silent option which only outputs the translation
uinput/deeplator pull request #6
Opened 2018-08-04 14:59 UTC by jonbulica99

Doing something like this:
`echo "Hello World" | python3 deeplator.py -l EN-DE` will output the following:
```
Enter the text to be translated. Use Ctrl+D to exit.
----------------
Hallo Welt
```
Most of the people who use this in scripting would appreciate a more sane output: e.g. `Hallo Welt` by supplying the argument `-s|--silent` in something that would look like this: 
`echo "Hello World" | python3 deeplator.py -l EN-DE -s` 
and would simply output what we are actually looking for: `Hallo Welt`.

2018-08-04 20:33 UTC, uinput requested changes

2018-08-04 20:33 UTC, uinput commented on deeplator.py
> +        if not args.silent: print("Enter the text to be translated. Use Ctrl+D to exit.", file=sys.stderr)
Could you add line breaks here?

2018-08-04 20:33 UTC, uinput commented on deeplator.py
> +        if not args.silent: print("-" * 16, file=sys.stderr)
And here too, please.

2018-08-04 21:02 UTC, jonbulica99 commented
Sorry @uinput, it should be fixed now. I forgot all about the python philosophy.

2018-08-05 16:32 UTC, uinput approved these changes

2018-08-05 16:33 UTC, merged